### ISSUE TITLE
Question: Interacting with the adapter from the View

### ISSUE THREAD

**Issue by mdocevski** [erikjhordan-rey/RecyclerView-Examples#1]
Hi
Just have a question about the interaction with the adapter and changing the underlying data. You have adapter.setItems in your View implementations. Shouldn't that be the job of the Presenter? That has me confused as I couldn't quite figure out where to put all the component's necesary for the RecyclerView. The RecyclerView itself according to the patter should definetly be a part of the MVP view. However the MVP presenter should do the data access modification business logic, and the actual data modification should be in the model, right? Is it that the way RecyclerView is set up that it cannot conform to MVP, or am I just going bonkers?

**Comment by erikjhordan-rey** [comment]
Maybe you can read my old post https://erikcaffrey.github.io/ANDROID-mvp/ Thankyou!
